### PR TITLE
return None if pretty in model archetype

### PR DESCRIPTION
**Pull request by ssssarah**
Some functions in the model archetype were returning an optional string, but for some cases in if statements there were no return statements

### CODE REVIEW

**Comment by crisely09** [comment]
Oh, but I think they should return the mappings if they exist, not `None`

**Comment by ssssarah** [comment]
Yes but that changes the behavior of things. I just made this for code quality

**Comment by crisely09** [comment]
OK, now they are consistent, they are either returned as strings or as dict, not both, correct?

**Comment by ssssarah** [comment]
The way I understand it is that if you specify pretty=True then you want it to be in the standard output stream and nothing is being returned, and it it's false you want it as a dict. But it's never returned as a str. I'm not against it but my goal with the MR was just to be explicit about the returning of nothing, not to change behavior

**Review by crisely09 — APPROVED** [review]
Fine with me.

**Pull request merged**
