### PR TITLE
travis.yml to release on PyPI

### PR DESCRIPTION
**Pull request by pafonta**

### CODE REVIEW

**Comment by pafonta** [comment]
Note: The build fails because the tests are not passing.

**Comment by pafonta** [comment]
NB: Force pushed a rebase on upstream/master to trigger a Travis build as a manual re-run was not working.

**Comment by pafonta** [comment]
Hello @MFSY,

As this is the first time I use Travis, I don't know why there are two builds and one seems stuck in 'queued' for more than 45 minutes.

It seems the PR could be merge though as it seems to pass according to [Travis dashboard](https://travis-ci.com/github/BlueBrain/nexus-forge/builds/176853511).

**Comment by MFSY** [comment]
The build is passing indeed. Please merge.

**Pull request merged**
