### PR TITLE
return resources  as dictionaries when forge.elastic if as_resource = False

### PR DESCRIPTION
**Pull request by ssssarah**
[DKE-1296](https://bbpteam.epfl.ch/project/issues/browse/DKE-1296)

### CODE REVIEW

**Review by lecriste — APPROVED** [review]
LGTM

**Comment by crisely09** [comment]
Could you add an example/script/notebook/test?

**Comment by ssssarah** [comment]
> Could you add an example/script/notebook/test?

I've added a couple of cells in the Getting started - 04 Querying notebook

**Review by crisely09 — APPROVED** [review]
Fine with me

**Pull request merged**
