### PR TITLE
Add GitHub actions and replace Travis

### PR DESCRIPTION
**Pull request by kplatis**
This pull request introduces 2 Github Actions that replace the existing Travis configuration:

1. `test.yml` that runs the unit tests and uploads the results. It runs when a change is pushed in any branch.
2. `publish.yml` that builds the tarball and publishes the package in PyPI. The PyPI token is [already set ](https://bbpteam.epfl.ch/project/issues/browse/HELP-14898). It runs when a new tag is pushed.

### CODE REVIEW

**Comment by kplatis** [comment]
@MFSY Should I also remove the already existing Travis configuration?

**Comment by kplatis** [comment]
@MFSY According to [this post](https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/13), there is no way to trigger tests when a pull request is merged. The only thing we can do is to restrict the branches in which the tests will run when pushed (merged)

**Comment by MFSY** [comment]
Hi @kplatis ,

I see. I think running the tests on the PR itself and restricting who can merge is okay.

**Review by MFSY — COMMENTED** [review]
I recommend to delete the .travis.yml file.

**Review by MFSY — APPROVED** [review]

**Pull request merged**
